USE fotology_app;

CREATE TABLE fotografo(
id BIGINT PRIMARY KEY AUTO_INCREMENT,
email VARCHAR(180) NOT NULL UNIQUE,
username VARCHAR(90) NOT NULL,
adress VARCHAR(90) NOT NULL UNIQUE,
image VARCHAR(255) NULL,
password VARCHAR(90) NOT NULL,
created_at TIMESTAMP(0) NOT NULL,
updated_at TIMESTAMP(0) NOT NULL

);